.\" xroma.1 - xroma man page
.TH xroma 1 "November 2023" "George Vlahavas" "xroma manual"

.SH NAME
xroma \- retrieve and display color information of a pixel on the screen

.SH SYNOPSIS
.B xroma
[\fB\-h\fR | \fB\-\-help\fR] [\fB\-\-hex\fR] [\fB\-c\fR \fIX,Y\fR]

.SH DESCRIPTION
\fBxroma\fR is a command-line tool for interacting with the X Window
System to retrieve and display the color information of a pixel on the
screen. By default it reads the color information for the pixel that is
under the mouse cursor, but you can also specify the coordinates of an
arbitrary pixel. The output is provided by default in a set of RGB
values (range 0-255), but you can also get it in hexadecimal format.

The name xroma comes from the greek word chroma, which means color. The
"ch" part is actually written with an X in greek, which is not pronounced
like an english X, but rather somewhat like the "ch" sound in chroma.

.SH OPTIONS
.TP
\fB\-h, \-\-help\fR
Print the help message.

.TP
\fB\-\-hex\fR
Print color in hexadecimal format.

.TP
\fB\-c, \-\-coordinates \fIX,Y\fR
Specify the coordinates (X,Y) to read the color from. The default
behavior is to retrieve the color information of the pixel that is under
the mouse cursor.

.SH EXAMPLE USAGE
Print the color information of the pixel under the mouse pointer:

.B xroma

Print the color information at specific coordinates:

.B xroma \-c 100,200

Print the color information in hexadecimal format:

.B xroma \-\-hex

.SH DEPENDENCIES
\fBxroma\fR depends on the Xlib library.

.SH LICENSE
This program is licensed under the GPLv3 License - see the COPYING file
for details.
